[project]
name = "llm-zoomcamp-2026-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "natnaelzemne21@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
llm-zoomcamp-2026-code = "llm_zoomcamp_2026_code:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
